sudo: required
services:
   - docker

script:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
   - docker build -t 3dpro/node:latest -f Dockerfile-debian .
   - docker tag 3dpro/node:latest 3dpro/node:debian
   - docker push 3dpro/node:latest
   - docker push 3dpro/node:debian
   - docker build -t 3dpro/node:8 -f Dockerfile-8 .
   - docker push 3dpro/node:8
   - docker build -t 3dpro/node:9 -f Dockerfile-9 .
   - docker push 3dpro/node:9
   - docker build -t 3dpro/node:10 -f Dockerfile-10 .
   - docker push 3dpro/node:10
   - docker build -t 3dpro/node:11 -f Dockerfile-11 .
   - docker push 3dpro/node:11
