FROM 3dpro/base-debian

ADD build-files /build-files
RUN wget -qO- https://deb.nodesource.com/setup_12.x | bash - && \
    apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg && \
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -y sudo vim nodejs yarn git && \
    mv /build-files/start.sh /start.sh && \
    yarn global add pm2 && \
    mkdir /opt/app && \
    mv /build-files/app.js /opt/app/app.js && \
    mv /build-files/process.yml /opt/app/process.yml && \
    cd /opt/app && yarn add express && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /build-files /etc/apt/apt.conf.d/11proxy

CMD ["/start.sh"]

EXPOSE 3000
